// Generated by scripts/generate-resolution-catalog.mjs — do not edit by hand.
export type ResolutionGroup = {
	id: string;
	label: string;
	options: readonly { value: Resolution; label: string }[];
};

export const resolutionGroups = [
	{
		id: '16:9',
		label: '16:9',
		options: [
			{
				value: '3840x2160',
				label: '3840×2160'
			},
			{
				value: '3200x1800',
				label: '3200×1800'
			},
			{
				value: '2560x1440',
				label: '2560×1440'
			},
			{
				value: '2048x1152',
				label: '2048×1152'
			},
			{
				value: '1920x1080',
				label: '1920×1080'
			},
			{
				value: '1600x900',
				label: '1600×900'
			},
			{
				value: '1280x720',
				label: '1280×720'
			}
		] as const
	},
	{
		id: '5:3',
		label: '5:3',
		options: [
			{
				value: '1280x768',
				label: '1280×768'
			}
		] as const
	},
	{
		id: '8:5',
		label: '8:5',
		options: [
			{
				value: '2560x1600',
				label: '2560×1600'
			},
			{
				value: '2048x1280',
				label: '2048×1280'
			},
			{
				value: '1920x1200',
				label: '1920×1200'
			},
			{
				value: '1680x1050',
				label: '1680×1050'
			},
			{
				value: '1440x900',
				label: '1440×900'
			},
			{
				value: '1280x800',
				label: '1280×800'
			}
		] as const
	},
	{
		id: '25:16',
		label: '25:16',
		options: [
			{
				value: '3200x2048',
				label: '3200×2048'
			},
			{
				value: '1600x1024',
				label: '1600×1024'
			}
		] as const
	},
	{
		id: '3:2',
		label: '3:2',
		options: [
			{
				value: '1920x1280',
				label: '1920×1280'
			},
			{
				value: '1440x960',
				label: '1440×960'
			}
		] as const
	},
	{
		id: '4:3',
		label: '4:3',
		options: [
			{
				value: '2560x1920',
				label: '2560×1920'
			},
			{
				value: '2048x1536',
				label: '2048×1536'
			},
			{
				value: '1920x1440',
				label: '1920×1440'
			},
			{
				value: '1600x1200',
				label: '1600×1200'
			},
			{
				value: '1440x1080',
				label: '1440×1080'
			},
			{
				value: '1400x1050',
				label: '1400×1050'
			},
			{
				value: '1024x768',
				label: '1024×768'
			},
			{
				value: '800x600',
				label: '800×600'
			},
			{
				value: '640x480',
				label: '640×480'
			},
			{
				value: '320x240',
				label: '320×240'
			}
		] as const
	},
	{
		id: '5:4',
		label: '5:4',
		options: [
			{
				value: '2560x2048',
				label: '2560×2048'
			},
			{
				value: '1280x1024',
				label: '1280×1024'
			}
		] as const
	},
	{
		id: '12:5',
		label: '12:5',
		options: [
			{
				value: '3840x1600',
				label: '3840×1600'
			}
		] as const
	},
	{
		id: '43:18',
		label: '43:18',
		options: [
			{
				value: '3440x1440',
				label: '3440×1440'
			}
		] as const
	},
	{
		id: '64:27',
		label: '64:27',
		options: [
			{
				value: '2560x1080',
				label: '2560×1080'
			}
		] as const
	}
] as const satisfies readonly ResolutionGroup[];

export const resolutionCatalog = [
	{
		value: '3840x2160',
		width: 3840,
		height: 2160,
		pixels: 8_294_400,
		pixelLabel: '3840×2160',
		aspectRatio: '16:9',
		aspectRatioValue: 16 / 9
	},
	{
		value: '3200x1800',
		width: 3200,
		height: 1800,
		pixels: 5_760_000,
		pixelLabel: '3200×1800',
		aspectRatio: '16:9',
		aspectRatioValue: 16 / 9
	},
	{
		value: '2560x1440',
		width: 2560,
		height: 1440,
		pixels: 3_686_400,
		pixelLabel: '2560×1440',
		aspectRatio: '16:9',
		aspectRatioValue: 16 / 9
	},
	{
		value: '2048x1152',
		width: 2048,
		height: 1152,
		pixels: 2_359_296,
		pixelLabel: '2048×1152',
		aspectRatio: '16:9',
		aspectRatioValue: 16 / 9
	},
	{
		value: '1920x1080',
		width: 1920,
		height: 1080,
		pixels: 2_073_600,
		pixelLabel: '1920×1080',
		aspectRatio: '16:9',
		aspectRatioValue: 16 / 9
	},
	{
		value: '1600x900',
		width: 1600,
		height: 900,
		pixels: 1_440_000,
		pixelLabel: '1600×900',
		aspectRatio: '16:9',
		aspectRatioValue: 16 / 9
	},
	{
		value: '1280x720',
		width: 1280,
		height: 720,
		pixels: 921_600,
		pixelLabel: '1280×720',
		aspectRatio: '16:9',
		aspectRatioValue: 16 / 9
	},
	{
		value: '1280x768',
		width: 1280,
		height: 768,
		pixels: 983_040,
		pixelLabel: '1280×768',
		aspectRatio: '5:3',
		aspectRatioValue: 5 / 3
	},
	{
		value: '2560x1600',
		width: 2560,
		height: 1600,
		pixels: 4_096_000,
		pixelLabel: '2560×1600',
		aspectRatio: '8:5',
		aspectRatioValue: 8 / 5
	},
	{
		value: '2048x1280',
		width: 2048,
		height: 1280,
		pixels: 2_621_440,
		pixelLabel: '2048×1280',
		aspectRatio: '8:5',
		aspectRatioValue: 8 / 5
	},
	{
		value: '1920x1200',
		width: 1920,
		height: 1200,
		pixels: 2_304_000,
		pixelLabel: '1920×1200',
		aspectRatio: '8:5',
		aspectRatioValue: 8 / 5
	},
	{
		value: '1680x1050',
		width: 1680,
		height: 1050,
		pixels: 1_764_000,
		pixelLabel: '1680×1050',
		aspectRatio: '8:5',
		aspectRatioValue: 8 / 5
	},
	{
		value: '1440x900',
		width: 1440,
		height: 900,
		pixels: 1_296_000,
		pixelLabel: '1440×900',
		aspectRatio: '8:5',
		aspectRatioValue: 8 / 5
	},
	{
		value: '1280x800',
		width: 1280,
		height: 800,
		pixels: 1_024_000,
		pixelLabel: '1280×800',
		aspectRatio: '8:5',
		aspectRatioValue: 8 / 5
	},
	{
		value: '3200x2048',
		width: 3200,
		height: 2048,
		pixels: 6_553_600,
		pixelLabel: '3200×2048',
		aspectRatio: '25:16',
		aspectRatioValue: 25 / 16
	},
	{
		value: '1600x1024',
		width: 1600,
		height: 1024,
		pixels: 1_638_400,
		pixelLabel: '1600×1024',
		aspectRatio: '25:16',
		aspectRatioValue: 25 / 16
	},
	{
		value: '1920x1280',
		width: 1920,
		height: 1280,
		pixels: 2_457_600,
		pixelLabel: '1920×1280',
		aspectRatio: '3:2',
		aspectRatioValue: 3 / 2
	},
	{
		value: '1440x960',
		width: 1440,
		height: 960,
		pixels: 1_382_400,
		pixelLabel: '1440×960',
		aspectRatio: '3:2',
		aspectRatioValue: 3 / 2
	},
	{
		value: '2560x1920',
		width: 2560,
		height: 1920,
		pixels: 4_915_200,
		pixelLabel: '2560×1920',
		aspectRatio: '4:3',
		aspectRatioValue: 4 / 3
	},
	{
		value: '2048x1536',
		width: 2048,
		height: 1536,
		pixels: 3_145_728,
		pixelLabel: '2048×1536',
		aspectRatio: '4:3',
		aspectRatioValue: 4 / 3
	},
	{
		value: '1920x1440',
		width: 1920,
		height: 1440,
		pixels: 2_764_800,
		pixelLabel: '1920×1440',
		aspectRatio: '4:3',
		aspectRatioValue: 4 / 3
	},
	{
		value: '1600x1200',
		width: 1600,
		height: 1200,
		pixels: 1_920_000,
		pixelLabel: '1600×1200',
		aspectRatio: '4:3',
		aspectRatioValue: 4 / 3
	},
	{
		value: '1440x1080',
		width: 1440,
		height: 1080,
		pixels: 1_555_200,
		pixelLabel: '1440×1080',
		aspectRatio: '4:3',
		aspectRatioValue: 4 / 3
	},
	{
		value: '1400x1050',
		width: 1400,
		height: 1050,
		pixels: 1_470_000,
		pixelLabel: '1400×1050',
		aspectRatio: '4:3',
		aspectRatioValue: 4 / 3
	},
	{
		value: '1024x768',
		width: 1024,
		height: 768,
		pixels: 786_432,
		pixelLabel: '1024×768',
		aspectRatio: '4:3',
		aspectRatioValue: 4 / 3
	},
	{
		value: '800x600',
		width: 800,
		height: 600,
		pixels: 480_000,
		pixelLabel: '800×600',
		aspectRatio: '4:3',
		aspectRatioValue: 4 / 3
	},
	{
		value: '640x480',
		width: 640,
		height: 480,
		pixels: 307_200,
		pixelLabel: '640×480',
		aspectRatio: '4:3',
		aspectRatioValue: 4 / 3
	},
	{
		value: '320x240',
		width: 320,
		height: 240,
		pixels: 76_800,
		pixelLabel: '320×240',
		aspectRatio: '4:3',
		aspectRatioValue: 4 / 3
	},
	{
		value: '2560x2048',
		width: 2560,
		height: 2048,
		pixels: 5_242_880,
		pixelLabel: '2560×2048',
		aspectRatio: '5:4',
		aspectRatioValue: 5 / 4
	},
	{
		value: '1280x1024',
		width: 1280,
		height: 1024,
		pixels: 1_310_720,
		pixelLabel: '1280×1024',
		aspectRatio: '5:4',
		aspectRatioValue: 5 / 4
	},
	{
		value: '3840x1600',
		width: 3840,
		height: 1600,
		pixels: 6_144_000,
		pixelLabel: '3840×1600',
		aspectRatio: '12:5',
		aspectRatioValue: 12 / 5
	},
	{
		value: '3440x1440',
		width: 3440,
		height: 1440,
		pixels: 4_953_600,
		pixelLabel: '3440×1440',
		aspectRatio: '43:18',
		aspectRatioValue: 43 / 18
	},
	{
		value: '2560x1080',
		width: 2560,
		height: 1080,
		pixels: 2_764_800,
		pixelLabel: '2560×1080',
		aspectRatio: '64:27',
		aspectRatioValue: 64 / 27
	}
] as const;

export type Resolution = (typeof resolutionCatalog)[number]['value'];

export const defaultResolution = '1920x1080' satisfies Resolution;

/** Flat list of resolutions in grouped-select order. */
export const resolutions = resolutionGroups.flatMap((group) => group.options);
